# Generated by Django 3.1.7 on 2021-08-07 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieApp', '0005_auto_20210807_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
