# Generated by Django 3.1.7 on 2021-08-07 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieApp', '0007_auto_20210807_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 4, 55, 45, 378914, tzinfo=utc)),
        ),
    ]
