# Generated by Django 3.1.7 on 2021-08-07 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieApp', '0008_auto_20210807_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_goal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 5, 3, 42, 886058, tzinfo=utc)),
        ),
    ]
