# Generated by Django 3.1.7 on 2021-08-07 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieApp', '0009_auto_20210807_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_goal',
            field=models.FloatField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 5, 33, 20, 103206, tzinfo=utc)),
        ),
    ]
